//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimationEditorCore.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsShowPreviousOnionSkinsEnabled {
            get {
                return ((bool)(this["IsShowPreviousOnionSkinsEnabled"]));
            }
            set {
                this["IsShowPreviousOnionSkinsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsShowNextOnionSkinsEnabled {
            get {
                return ((bool)(this["IsShowNextOnionSkinsEnabled"]));
            }
            set {
                this["IsShowNextOnionSkinsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PreviousFrameSkinCount {
            get {
                return ((int)(this["PreviousFrameSkinCount"]));
            }
            set {
                this["PreviousFrameSkinCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NextFramesSkinCount {
            get {
                return ((int)(this["NextFramesSkinCount"]));
            }
            set {
                this["NextFramesSkinCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double PreviousFrameSkinOpacityFalloff {
            get {
                return ((double)(this["PreviousFrameSkinOpacityFalloff"]));
            }
            set {
                this["PreviousFrameSkinOpacityFalloff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double NextFrameSkinOpacityFalloff {
            get {
                return ((double)(this["NextFrameSkinOpacityFalloff"]));
            }
            set {
                this["NextFrameSkinOpacityFalloff"] = value;
            }
        }
    }
}
